site:
  title: Concurrency Deep Dives
  url: https://cmhteixeira.com/concurrency
content:
  sources:
    - url: .
ui:
  bundle:
    url:  https://github.com/cmhteixeira/concurrency-site-ui-bundle/releases/download/refs%2Fheads%2Fmaster/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui