site:
  title: Concurrency Deep Dives
  url: https://cmhteixeira.com/concurrency
content:
  sources:
    - url: .
ui:
  bundle:
    url: https://github.com/cmhteixeira/concurrency-site-ui-bundle/releases/download/7/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental-ui